config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'  # end

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  devise_for :accounts, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'accounts/omniauth_callbacks'}
  scope "(:locale)" do
    root to: 'dashboard#index'
    resources :personas, only: [:index]

    resources :user_passwords, path: 'user/password'

    get '/get_states', to: 'csc#get_states', as: :get_states
    get '/get_cities', to: 'csc#get_cities', ad: :get_cities

    get 'dashboard/index'
    get 'not_found', to: 'errors#not_found'

    resource :dashboard, controller: 'dashboard' do
      collection do
        get :active
        get :draft
        get :finished
      end
    end


    devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, skip: :omniauth_callbacks

    resources :users, path: 'account/users'
    get 'accept_invitation/:id', to: "users#accept_invitation", as: :accept_invitation

    resources :account_settings, except: [:new, :index, :create, :edit, :update, :destroy] do
      member do
        delete :delete_image_attachment
      end
      collection do
        post :overview_update
        post :settings_update
        post :new_billing_email
        post :update_billing_email
      end
    end

    get 'dashboard/settings'

    match '/account_settings', to: 'account_settings#settings', via: :get
    resources :users do
      member do
        put :update_user
        get :resend_invitation
      end
    end

    scope 'account', as: 'account' do
      resources :users
    end

    scope 'account_settings', as: 'account_settings' do
      resources :users
    end
 
    resources :groups, except: [:show] do
      collection do
        get :choose_template
        get :choose_template_tab
        get :industry_themes
        get :destroy_template
      end

      resources :surveys, controller: 'groups/surveys' do
        member do
          get :results
        end

        collection do
          get :all
          get :finished
          get :active
          get :draft
        end
      end
    end

    resources :customized_personas do
      collection do
        get :export_pdf
      end
    end

    resources :reports do
      resources :surveys, controller: 'reports/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end
    
    resources :results do
      resources :surveys, controller: 'results/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end

    get 'persona_display_type/:display_type_id', to: 'persona_display_types#display_type', as: :persona_display_type

    get 'survey/:survey_token', to: 'survey_submissions#start', as: :public_survey
    post 'survey/continue', to: 'survey_submissions#continue', as: :public_survey_continue
    get 'survey/submit', to: 'survey_submissions#new', as: :public_survey_new

    get 'survey/:survey_token/:encr_mail_id', to: 'survey_submissions#start', as: :encr_mail_survey_open

    post 'survey/screen', to: 'survey_submissions#screen_submit', as: :public_survey_screen

    resources :survey_submissions, except: [:index]

    resources :surveys, controller: 'surveys' do
      member do
        get :success
        get :preview_survey
        get :preview_survey_branching
        get :save_as_a_template
        post :save_as_a_template_create
        get :respondent_with_answers
        get :disable_or_enable_shared_link
      end

      collection do
        get :new_group
        post :create_group

        get :clone
        post :clone_submit

        get :move
        post :move_submit

        get :duplicate
        post :duplicate_submit
      end

      resources :steps, controller: 'surveys/steps'

      resources :categories_surveys, controller: 'surveys/categories_surveys' do
        collection do
          get :new_list_modal
          post :create_list

          get :new_recipient_modal
          post :create_recipient

          get :add_block_modal

          get :remove_custom_block

          get :clone_block_modal
          post :clone_block

          get :save_as_block_modal
          post :save_as_block_submit

          get :edit_block_modal
          patch :edit_block

          get :delete_question

          get :new_question
          post :new_question_submit

          get :duplicate_question

          get :edit_question
          patch :update_question

          get :get_group_by_question_types_templates

          get :reset
        end
      end
    end

    resources :lists do
      resources :recipients
    end


    match '/admin', to: 'admin#dashboard', via: :get
    namespace :admin do

      resources :accounts do
        collection do
          get :activate_or_disable
          get :okta_enable
          get :okta_disable
          post :add_trial_submit
        end
        member do
          get :reinstate
        end
      end

      resources :industries

      resources :template_themes do
        member do
          get :preview
          
          get :clone_template_modal 
          post :clone_template
        end

        resources :steps, controller: 'template_themes/steps' do
          collection do
            get :preview_survey
          end
        end

        resources :template_categories, controller: 'template_themes/categories_template_themes' do
          collection do
            get :preview_survey

            get :add_block_modal

            get :clone_block_modal
            post :clone_block

            get :edit_block_modal
            patch :edit_block

            get :delete_question
            get :edit_question
            patch :update_question

            get :get_group_by_question_types_templates

            get :reset
          end
        end

      end

      resources :categories, path: 'block-templates' do
        member do
          get :preview

          get :clone_block_modal
          post :clone_block
        end
        resources :questions, controller: 'categories/questions'
      end

      resources :label_templates do
        collection do
          get :get_group_by_question_types_templates
          get :get_template_description
        end
      end

    end
  end

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :trackable, :omniauthable, omniauth_providers: [:oktaoauth]

  validates_presence_of :your_name
  validates_presence_of :company_name, :company_email, if: lambda { |o| o.company == true }
  validates_presence_of :sender_email, if: lambda { |o| o.company == false }

  has_many :users, dependent: :destroy
  has_many :admin_users, class_name: "User", foreign_key: "account_id"

  has_many :template_themes, dependent: :destroy

  has_many :categories, dependent: :destroy

  has_many :groups, dependent: :destroy

  has_many :lists, dependent: :destroy
  has_many :recipients, dependent: :destroy


  has_one :account_setting
  has_and_belongs_to_many :email_notification_types

  has_one_attached :image
  has_one_attached :company_image

  enum login_options: [ :normal, :okta ]

  def active_for_authentication?
    super and if self.account_type == 'client'
                self.allowed_to_log_in?
              elsif account_type == 'user'
                self.allowed_to_log_in? and self.active == 1 and self.archived == false
              end
  end

  def self.from_omniauth(auth)
    account = Account.find_by(email: auth["info"]["email"])
    if account.blank?
      account = Account.new
      account.provider = auth['provider']
      account.uid = auth['uid']
      account.email = auth['info']['email']
      account.your_name = auth['info']['name']
      account.company = false
      account.sender_email = auth['info']['email']
      account.save(validate: false)
    else
      account.provider = auth['provider']
      account.uid = auth['uid']
      account.save(validate: false)
    end
    account
  end

  def send_devise_notification(notification, *args)
    unless(notification == :password_change && sign_in_count.zero? && invitation_code.present?)
      super
    end
  end
end

app/models/account_setting.rb
class AccountSetting < ApplicationRecord
  belongs_to :account
  belongs_to :industry
  serialize :billings_emails, JSON
  EMPLOYEE_COUNT = ["1 to 50", "51 to 100", "101 to 200", ">200"]
end

app/controllers/account_settings_controller.rb
class AccountSettingsController < ApplicationController
  require 'will_paginate/array'
  def settings
    @per_page = params[:per_page].present? ? params[:per_page] : 10

    if $community_account.company
      @company_name = $community_account.company_name
      @company_email = $community_account.company_email
    else
      @company_name = "#{t 'account_settings.dont_know_company_name'}"
      @company_email = "#{t 'account_settings.dont_know_company_email'}"
    end
    @created_by = $community_account.your_name
    @created_at = $community_account.created_at
    # if params[:sort].present?
    #   users = $community_account.users.where(archived: false).includes(:account).order(params[:sort].downcase)
    #   @users = users.paginate(page: params[:page], per_page: @per_page)
    #   @account_users = users 
    # else
      @account_users = $community_account.users.where(archived: false).includes(:account)
      @users = Account.where(id: $community_account.id) + @account_users
      @users = @users.paginate(page: params[:page], per_page: @per_page)
    # end
    @pending_users = @account_users.where(active: "pending").where(allowed_to_log_in: true).count
    @disabled_users = @account_users.where(allowed_to_log_in: false).count
    @active_users = @account_users.where(active: "active").where(allowed_to_log_in: true).count
    @settings = $community_account.account_setting || AccountSetting.new
    @admin_users = $community_account.users.where(role: "admin")
  end

  def overview_update
    authorize $community_account, :owner_access?, policy_class: AccountPolicy

    if params["company_image"]
      $community_account.company_image.attach(params["company_image"])
    end

    begin
      AccountSetting.find_or_initialize_by(account_id: $community_account.id).update(overview_params)
      redirect_to account_settings_path
    rescue
      flash[:danger] = "Something went wrong"
      redirect_to account_settings_path
    end
  end

  def settings_update
    authorize $community_account, :owner_access?, policy_class: AccountPolicy

    account = $community_account
    begin
      admin_ids = settings_params[:admin_user_ids] << account.id.to_s
      accounts = Account.where(id: admin_ids)
      accounts.update_all(company_email: settings_params[:company_email], company_name: settings_params[:company_name])
      redirect_to account_settings_path(tab: 'settings')
    rescue
      flash[:danger] = "Something went wrong"
      redirect_to account_settings_path(tab: 'settings')
    end
  end

  def delete_image_attachment
    authorize $community_account, :owner_access?, policy_class: AccountPolicy

    @image = ActiveStorage::Blob.find_signed(params[:id])
    @image.attachments.first.purge_later
    redirect_back(fallback_location: root_path)
  end

  def new_billing_email
    authorize $community_account, :owner_access?, policy_class: AccountPolicy

    new_email = params[:account_setting][:billing_emails]
    if $community_account.account_setting.billing_emails.present?
      $community_account.account_setting.billing_emails
      new_hash = $community_account.account_setting.billing_emails
      new_hash[(new_hash.count+1)] = new_email
      $community_account.account_setting.update(billing_emails: new_hash)
    else
      $community_account.account_setting.update(billing_emails: {0=> new_email})
    end
    redirect_back(fallback_location: root_path)
  end

  def update_billing_email
    authorize $community_account, :owner_access?, policy_class: AccountPolicy

    emails = params[:billing_email].values
    new_hash = {}
    emails.each_with_index do |x,i|
      new_hash[i] = x
    end
    $community_account.account_setting.update(billing_emails: new_hash)
  end

  private

  def overview_params
    params.require(:account_setting).permit(:industry_id,:no_of_employees)
  end

  def settings_params
    params.require(:account).permit(:company_name, :company_email, admin_user_ids: [])
  end
end

app/views/account_settings/_billing_section.html.erb
  <div id="menu2" class="container tab-pane fade"><br>
    <div class="row m-0">
      <div class="col-md-12">
        <div class="col-md-9 mx-auto">
          <h4 class="settings-inner">Your Plan</h4>
        </div>
        <div class="col-md-7 mx-auto">
          <h3 class="premium-plan">Premium plan</h3>
          <p class="you-ve-sent-5-survey">You’ve sent 5 surveys, 2 surveys remaining  <button class="btn-upgrade-plan"> Upgrade plan</button></p>
          <p class="next-payment">Next payment is $2,500 on 01 Nov, 2019</p>
          <a href="#" class="view-bill">View billing history</a>
        </div>
        <div class="col-md-9 mx-auto">
          <h4 class="settings-inner">Payment Method</h4>
        </div>
        <div class="col-md-8 mx-auto">
          <div class="row">
            <div class="col-6">
              <div class="cards active">
                <div class="card-overlay">
                  <div class="card-overlay-icons">
                    <i class="fas fa-pen"></i>
                    <i class="fas fa-trash"></i>
                  </div>
                </div>
                <h4 class="card-name">Visa</h4>
                <p class="card-number">34XX XXXX XXXX XX98<p>
                  <p class="exp-date">Exp date  09/20</p>
                  <p class="card-user-name">Vibes Elastic</p>
                </div>
              </div>
              <div class="col-6">
                <div class="cards">
                  <div class="card-overlay">
                    <button class="btn-setdefault">Set as default payment</button>
                    <div class="card-overlay-icons">
                      <i class="fas fa-pen"></i>
                      <i class="fas fa-trash"></i>
                    </div>
                  </div>
                  <h4 class="card-name">Paypal</h4>
                  <p class="card-number">Vibes Elastic<p>
                    <p class="card-number pt-0">account@account.com</p>
                  </div>
                </div>
                <div class="col-6">
                  <div class="cards add-cards">
                    <i class="fas fa-plus-circle"></i>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-9 mx-auto">
              <h4 class="settings-inner">Billing Info</h4>
            </div>
            <%= form_for @settings, url: update_billing_email_account_settings_path, method: :post do |f|%>
            <%if @settings.billing_emails.present? %>
              <% @settings.billing_emails.values.each_with_index do |e, i|%>
                <div class="col-md-5 mx-auto">
                  <div class="form-group">
                    <label>Your Email Address</label>
                    <input type="text" class="field" name="billing_email[<%=i%>]" value="<%=e%>">
                  </div>
                </div>
              <% end %>
            <% else%>
              <div class="col-md-5 mx-auto">
                <div class="form-group">
                  <label>Your Email Address</label>
                  <input type="text" class="field" name="billing_email[0]" value="<%= $community_account.email %>">
                </div>
              </div>
            <% end %>
            <div class="add-more col-md-5 mx-auto" data-toggle="modal" data-target="#UpdateBillingEmailModal">
              <i class="fas fa-plus-circle"></i>  Add new billing email
            </div>
            <div class="col-md-9 mx-auto">
              <h4 class="settings-inner">Billing History</h4>
            </div>
            <div class="col-md-8 mx-auto">
              <table class="table-1">
                <tr>
                  <td class="td1">01 Oct 2019</td>
                  <td class="td2" align="right">$ 2,500 <a href="#" class="print">Print</a></td>
                </tr>
                <tr>
                  <td class="td1">01 Sep 2019</td>
                  <td class="td2" align="right">$ 2,500</td>
                </tr>
                <tr>
                  <td class="td1">01 Aug 2019</td>
                  <td class="td2" align="right">$ 2,500</td>
                </tr>
                <tr>
                  <td class="td1">01 Jul 2019</td>
                  <td class="td2" align="right">$ 2,500</td>
                </tr>
                <tr>
                  <td class="td1">01 Jun 2019</td>
                  <td class="td2" align="right">$ 2,500</td>
                </tr>
              </table>

              <button class="btn btn-common" style="margin-top:3em; margin-bottom:2em;">Update</button>

              <% end %>
            </div>
          </div>
        </div>
      </div>

app/views/account_settings/_delete_user_modal.html.erb
<div class="modal fade delete-user-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">

  <div class="modal-dialog modal-md">
    <div class="modal-content">

      <div class="modal-body">
        <h2><%= t 'account_settings.are_you_sure_you_want_to_delete'%><br><span id="delete_user_name">“Marvin Schneider” ?</span></h2>
         <!-- <button class="btn btn-cancel" href="#" id= "delete_user">Yes, delete</button> -->
         <%=link_to "#{t 'account_settings.yes_delete'}", "#",:method => 'delete', class: "btn-cancel", id: 'delete_user', style: "font-size: 16px;"%>
        <button class="btn btn-common" style="font-size: 16px;" data-dismiss="modal"><%= t 'account_settings.no_do_not_delete'%></button>

      </div>
    </div>
  </div>
</div>

app/views/account_settings/_overview_form.html.erb
<div id="home" class="container tab-pane active"><br>
  <div class="row m-0">
    <div class="col-md-12">
      <%= form_for @settings, url: overview_update_account_settings_path, method: :post, html:{multipart: true}  do |f| %>
        <div class="col-md-7 mx-auto">
          <div class="col-md-12 mx-auto">
            <div class="row user-wrap">
              <% if $community_account.company_image.attached? %>
                <div class="profile-image col" style="<%= "background: url(#{asset_path(url_for($community_account.company_image))} )" if $community_account.company_image.attached? %>" >
                  <% if policy($community_account).admin_access? %>
                    <div class="profile-image-upload" >
                      <div class="upload-btn-wrapper">
                        <button class="profile-image-upload-button"><%= t 'account_settings.update'%></button>
                        <input type="file" name="company_image" id="company_image" />
                      </div>
                      <!-- <button class="remove-image">Remove</button> -->
                      <%= link_to "#{t 'account_settings.remove'}", delete_image_attachment_account_setting_path($community_account.company_image.signed_id), method: :delete, data: { confirm: "#{t 'account_settings.are_you_sure'}" }, class: "remove-image" %>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <div class="profile-image col" >
                  <div class="profile-image-upload" >
                    <div class="upload-btn-wrapper">
                      <button class="profile-image-upload-button"><%= t 'account_settings.update'%></button>
                      <input type="file" name="company_image" id="company_image" />
                    </div>
                  </div>
                </div>
              <% end %>
              <div class="profile-user-name col">
                <h4><%= @company_name%></h4>
                <p><%= @company_email%></p>
                <p><%= t 'account_settings.joined'%> <%= @created_at.strftime("%b %d, %Y")%></p>
                <p><%= t 'account_settings.created_by'%> <%= @created_by%></p>
              </div>
            </div>
          </div>
        </div>

        <% if policy($community_account).admin_access? %>

          <div style="display: none">
            <div class="col-md-9 mx-auto">
              <h4 class="settings-inner">Overview</h4>
            </div>
            <div class="col-md-7 mx-auto">
              <h3 class="premium-plan">Premium plan</h3>
              <p class="you-ve-sent-5-survey">You’ve sent 5 surveys, 2 surveys remaining  <button class="btn-upgrade-plan"> Upgrade plan</button></p>
              <p class="next-payment">Next payment is $2,500 on 01 Nov, 2019</p>
              <a href="#" class="view-bill" onclick="showBilling()">View billing history</a>
            </div>
          </div>

          <div class="col-md-9 mx-auto">
            <h4 class="settings-inner"><%= t 'account_settings.help_us_improve'%></h4>
          </div>

          <div class="col-md-7 mx-auto">
            <div class="form-group">
              <label><%= t 'account_settings.your_industry'%></label>
              <%= f.select :industry_id, Industry.all.collect { |d| [ d.title, d.id ] },{include_blank: true},{class: "field"} %>
            </div>

            <div class="form-group">
              <label><%= t 'account_settings.no_of_employees'%></label>
              <%= f.select :no_of_employees, AccountSetting::EMPLOYEE_COUNT, {include_blank: true}, {class: "field"} %>
            </div>
            <button class="btn btn-common" style="margin-top:2em; margin-bottom:2em;"><%= t 'account_settings.update'%></button>
          </div>
        <% else %>
          <div class="col-md-9 mx-auto">
            <h4 class="settings-inner"><%= t 'account_settings.help_us_improve'%></h4>
          </div>

          <div class="col-md-7 mx-auto">
            <div class="form-group">
              <label><%= t 'account_settings.your_industry'%></label> <br>
              <% begin %>
                <%= @settings.industry.title %>
              <% rescue %>
                N/A
              <% end %>
            </div>

            <div class="form-group">
              <label><%= t 'account_settings.no_of_employees'%></label> <br>
              <% begin %>
                <%= @settings.no_of_employees %>
              <% rescue %>
                N/A
              <% end %>
            </div>
          </div>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('.profile-image').css("background", "url("+e.target.result+")");
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#company_image").change(function(){
        readURL(this);
    });
</script>

app/views/account_settings/_settings_form.html.erb
<div id="menu1" class="container tab-pane fade"><br>
  <%= form_for $community_account, url: settings_update_account_settings_path, method: :post do |f| %>
  <div class="row m-0">
    <div class="col-md-12">
      <div class="col-md-9 mx-auto">
        <h4 class="settings-inner"><%= t 'account_settings.general'%></h4>
      </div>

      <div class="col-md-5 mx-auto">
        <div class="form-group">
          <label><%= t 'account_settings.company_name'%></label>
          <%= f.text_field :company_name, class: "field" %>
        </div>
        <div class="form-group">
          <label><%= t 'account_settings.sender_email_company_email'%></label>
          <%= f.text_field :company_email, class: "field" %>
        </div>
      </div>

      <div style="display: none">

      <div class="col-md-9 mx-auto">
        <h4 class="settings-inner">Account Admin</h4>
      </div>

      <div class="col-md-5 mx-auto admin-options">
        <div class="form-group add-blocks">
          <label>Admin</label>
        </div>
        <%= f.select :admin_user_ids, options_from_collection_for_select(@admin_users, :id, :your_name, $community_account.admin_users.pluck(:id)),
        {:include_blank => true}, {:multiple => true, class: "selectpicker multi-select"} %>
        <div class="add-more">
          <i class="fas fa-plus-circle"></i>  Add new admin
        </div>
      </div>
      </div>

      <div class="col-md-5 mx-auto">
        <%= f.submit "#{t 'account_settings.update'}", class: "btn btn-common", style: "margin-top:2em; margin-bottom:2em;"%>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/account_settings/_update_billing_email.erb
<div class="modal" id="UpdateBillingEmailModal" tabindex="-1" role="dialog" aria-labelledby="ListAddModalLabel">
  <div class="modal-dialog modal-lg modal-dialog-centered cgroup-pop-modal" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="cgroup-pop">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <div class="cgroup-pop-header text-center">
            <div class="cgroup-pop-header-title">Update New Billing Email</div>
          </div>
          <%= form_for @settings, url: new_billing_email_account_settings_path, method: :post do |f| %>
            <div class="cgroup-form">
              <%= f.label :billing_emails, 'Billing Email' %>
              <%= f.email_field :billing_emails, label: false, placeholder: '', required: true, focus: true, input_html: { required: true, class: 'input-field__input input--big' } %>
              <span class="text-mutued">Enter the billing email here.</span>
            </div>

            <%= f.button :submit, class: 'btn btn-common' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/account_settings/_user_details_popup.html.erb
<% presenter = UserPresenter.new(@user) %>
<%= form_for @user, url: update_user_user_path, method: :put, html: { multipart: true } do |f|%>
  <a href="#" class="close-u" onclick="hideUserDetails()"><i class="fas fa-angle-left"></i> <%= t 'account_settings.done'%></a>
  <div class="user-details-head">
    <div class="sidebar-user-img">
      <% if @user.image.attached? %>
        <div class="profile-image profile-image-user col" style="<%= "background: url(#{asset_path(url_for(@user.image))} )" if @user.image.attached? %>">
          <div class="profile-image-upload" >
            <div class="upload-btn-wrapper">
            <button class="profile-image-upload-button"><%= t 'account_settings.update'%></button>
            <input type="file" name="user[image]" id="user_image" />
          </div>
          <%=  link_to delete_image_attachment_account_setting_path(@user.image.signed_id), method: :delete, data: { confirm: "#{t 'account_settings.are_you_sure'}" } do %>
            <button class="remove-image"><%=t 'account_settings.remove'%></button>
          <% end %>
          </div>
        </div>
      <% else %>
        <div class="profile-image profile-image-user col" style="background: url(/assets/Avatar.png)">
          <div class="profile-image-upload" >
            <div class="upload-btn-wrapper">
              <button class="profile-image-upload-button"><%= t 'account_settings.update'%></button>
              <input type="file" name="user[image]" id="user_image" />
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <h2 class="user-name-only"><%= @user.your_name %><i class="fas fa-pen edit-user-ic user-edit" onclick="showUserNameField()"></i></h2>
    <h2 class="usr-name-field"><%= f.text_field :your_name, class: "user-name-edit" %></h2>
    <p class="user-email-only"><%= @user.email%><i class="fas fa-pen edit-user-ic user-edit" onclick="showUserEmailField()"></i></p>
    <p class="usr-email-field"><%=f.text_field :email, class: "user-name-edit" %></p>
    <h6><%= presenter.user_pending_section %></h6>
    <% if @user.pending? %>
      <%= link_to "#{t 'account_settings.resend_invitation'}", resend_invitation_user_path(@user), class: "invitation-btn" %>
    <% end %>
  </div>
  <div class="role-wrap">
    <%= f.select(:role, User.roles.keys.map {|role| [user_role_for_dropdown_locale(role),role]}, {}, class: "field")%>
  </div>

  <div class="role-wrap">
    <div class="row">
      <h4 style="font-size: 1.2rem;
          padding: 6px;
          margin-left: 13px;"><%= t 'account_settings.access'%>: </h4>

      <%= f.check_box :allowed_to_log_in,
                      :data => { :size=>'large', 'on-color'=>'warning', 'off-color'=>'danger', 'on-text'=>"#{t 'account_settings.enable'}", 'off-text'=>"#{t 'account_settings.disable'}" } %>
    </div>
  </div>

  <div style="margin-top:40px;">
    <button class="btn btn-common" type="submit" style="font-size: 14px;"><%= t 'account_settings.update'%> </button>
    <button class="btn btn-cancel" onclick="hideUserDetails()" type="button"><%= t 'account_settings.cancel'%> </button>
  </div>

<% end %>

<script type="text/javascript" charset="utf-8">
    $('#user_allowed_to_log_in').bootstrapSwitch();

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('.profile-image-user').css("background", "url("+e.target.result+")");
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#user_image").change(function(){
        readURL(this);
    });
</script>