config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'  # end

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  devise_for :accounts, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'accounts/omniauth_callbacks'}
  scope "(:locale)" do
    root to: 'dashboard#index'
    resources :personas, only: [:index]

    resources :user_passwords, path: 'user/password'

    get '/get_states', to: 'csc#get_states', as: :get_states
    get '/get_cities', to: 'csc#get_cities', ad: :get_cities

    get 'dashboard/index'
    get 'not_found', to: 'errors#not_found'

    resource :dashboard, controller: 'dashboard' do
      collection do
        get :active
        get :draft
        get :finished
      end
    end


    devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, skip: :omniauth_callbacks

    resources :users, path: 'account/users'
    get 'accept_invitation/:id', to: "users#accept_invitation", as: :accept_invitation

    resources :account_settings, except: [:new, :index, :create, :edit, :update, :destroy] do
      member do
        delete :delete_image_attachment
      end
      collection do
        post :overview_update
        post :settings_update
        post :new_billing_email
        post :update_billing_email
      end
    end

    get 'dashboard/settings'

    match '/account_settings', to: 'account_settings#settings', via: :get
    resources :users do
      member do
        put :update_user
        get :resend_invitation
      end
    end

    scope 'account', as: 'account' do
      resources :users
    end

    scope 'account_settings', as: 'account_settings' do
      resources :users
    end
 
    resources :groups, except: [:show] do
      collection do
        get :choose_template
        get :choose_template_tab
        get :industry_themes
        get :destroy_template
      end

      resources :surveys, controller: 'groups/surveys' do
        member do
          get :results
        end

        collection do
          get :all
          get :finished
          get :active
          get :draft
        end
      end
    end

    resources :customized_personas do
      collection do
        get :export_pdf
      end
    end

    resources :reports do
      resources :surveys, controller: 'reports/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end
    
    resources :results do
      resources :surveys, controller: 'results/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end

    get 'persona_display_type/:display_type_id', to: 'persona_display_types#display_type', as: :persona_display_type

    get 'survey/:survey_token', to: 'survey_submissions#start', as: :public_survey
    post 'survey/continue', to: 'survey_submissions#continue', as: :public_survey_continue
    get 'survey/submit', to: 'survey_submissions#new', as: :public_survey_new

    get 'survey/:survey_token/:encr_mail_id', to: 'survey_submissions#start', as: :encr_mail_survey_open

    post 'survey/screen', to: 'survey_submissions#screen_submit', as: :public_survey_screen

    resources :survey_submissions, except: [:index]

    resources :surveys, controller: 'surveys' do
      member do
        get :success
        get :preview_survey
        get :preview_survey_branching
        get :save_as_a_template
        post :save_as_a_template_create
        get :respondent_with_answers
        get :disable_or_enable_shared_link
      end

      collection do
        get :new_group
        post :create_group

        get :clone
        post :clone_submit

        get :move
        post :move_submit

        get :duplicate
        post :duplicate_submit
      end

      resources :steps, controller: 'surveys/steps'

      resources :categories_surveys, controller: 'surveys/categories_surveys' do
        collection do
          get :new_list_modal
          post :create_list

          get :new_recipient_modal
          post :create_recipient

          get :add_block_modal

          get :remove_custom_block

          get :clone_block_modal
          post :clone_block

          get :save_as_block_modal
          post :save_as_block_submit

          get :edit_block_modal
          patch :edit_block

          get :delete_question

          get :new_question
          post :new_question_submit

          get :duplicate_question

          get :edit_question
          patch :update_question

          get :get_group_by_question_types_templates

          get :reset
        end
      end
    end

    resources :lists do
      resources :recipients
    end


    match '/admin', to: 'admin#dashboard', via: :get
    namespace :admin do

      resources :accounts do
        collection do
          get :activate_or_disable
          get :okta_enable
          get :okta_disable
          post :add_trial_submit
        end
        member do
          get :reinstate
        end
      end

      resources :industries

      resources :template_themes do
        member do
          get :preview
          
          get :clone_template_modal 
          post :clone_template
        end

        resources :steps, controller: 'template_themes/steps' do
          collection do
            get :preview_survey
          end
        end

        resources :template_categories, controller: 'template_themes/categories_template_themes' do
          collection do
            get :preview_survey

            get :add_block_modal

            get :clone_block_modal
            post :clone_block

            get :edit_block_modal
            patch :edit_block

            get :delete_question
            get :edit_question
            patch :update_question

            get :get_group_by_question_types_templates

            get :reset
          end
        end

      end

      resources :categories, path: 'block-templates' do
        member do
          get :preview

          get :clone_block_modal
          post :clone_block
        end
        resources :questions, controller: 'categories/questions'
      end

      resources :label_templates do
        collection do
          get :get_group_by_question_types_templates
          get :get_template_description
        end
      end

    end
  end

end

app/models/categories_survey.rb
class CategoriesSurvey < ApplicationRecord
  include RailsSortable::Model
  set_sortable :position

  default_scope { order(position: :asc) }

  belongs_to :category
  belongs_to :survey
end

app/models/list.rb
class List < ApplicationRecord
  default_scope {order(created_at: :desc)}

  attr_accessor :multi_emails
  attr_reader :multi_emails

  belongs_to :account
  has_and_belongs_to_many :recipients
  has_and_belongs_to_many :surveys

  scope :not_deleted, -> {where(archived: false)}
end

app/models/survey.rb
class Survey < ApplicationRecord
  # default_scope {order(created_at: :desc)}

  attr_accessor :date_range
  attr_reader :date_range

  # FIXME add sender id to survey who activated survey also check for emails

  # FIXME use enum for survey_types
  # enum survey_type: {"Survey" => 0,
  #                        "" => 1,
  #                        "Persona" => 2}


  belongs_to :template_theme, optional: true
  belongs_to :group
  belongs_to :creator, class_name: 'Account', foreign_key: :created_by_id
  has_and_belongs_to_many :industries
  has_and_belongs_to_many :lists
  has_and_belongs_to_many :recipients
  has_many :categories, dependent: :destroy
  has_many :categories_surveys
  has_many :category_blocks, through: :categories_surveys, source: :category
  has_many :submissions, dependent: :destroy
  has_many :custom_personas, dependent: :destroy

  has_many :recipients_surveys
  has_many :allowed_recipients_surveys, -> { allowed_survey }, class_name: "RecipientsSurvey"

  accepts_nested_attributes_for :recipients_surveys, allow_destroy: true

  scope :undeleted_survey, -> { where("deleted_at IS NULL") }



  def recipients_surveys_for_form(survey_id, list_id, recipient_id)
    collection = recipients_surveys.where(list_id: list_id, recipient_id: recipient_id)
    collection.any? ? collection : recipients_surveys.build
  end

  enum survey_state: {"Draft" => 0,
                         "Active" => 1,
                         "Finished" => 2}

  enum persona_summary_display_types: {"Template 1" => 0, "Template 2" => 1}

  before_create :set_default_value
  after_save :set_delivery_time

  def set_default_value
    survey_token = Digest::SHA1.hexdigest([Time.now, rand].join)
    public_token = Digest::SHA1.hexdigest([Time.now, rand(34534656)].join)
    self.survey_token = survey_token
    self.public_token = public_token
    self.survey_state = 0
  end

  def aggregator
    SubmissionsAggregator.new(submissions: self.submissions,
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def pdf_aggregator submission_ids
    SubmissionsAggregator.new(submissions: self.submissions.where(id: submission_ids),
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def aggregator_scoring
    SubmissionsAggregatorScoring.new(submissions: self.submissions,
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def pdf_aggregator_scoring submission_ids
    SubmissionsAggregatorScoring.new(submissions: self.submissions.where(id: submission_ids),
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def customized_aggregator_scoring(submissions)
    CustomSubmissionsAggregatorScoring.new(submissions: submissions,
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def summary_calculator
    SurveySummaryCalculator.new(submissions: self.submissions, recipients: self.recipients_surveys.where(allow_survey: "true").pluck(:recipient_id).uniq)
  end

  def set_delivery_time
    survey = self
    unless delivery_time.blank?
      # p self.delivery_time.strftime("%Y-%m-%d")+ ' ' + @record.date_time.to_datetime.strftime('%H:%M:%S')
      unless self.delivery_start_at.blank?
        delivery_period = self.delivery_start_at.localtime.strftime("%Y-%m-%d")+ ' ' + self.delivery_time.localtime.strftime('%H:%M:%S') 
        self.update_column(:delivery_time, delivery_period)
      end
 
    end
  end

  def self.all_step_valid_survey(survey)
    if !survey.title.present?
      false
    elsif !survey.welcome_page.present?
      false
    elsif (!survey.lists.present? || !survey.recipients_surveys.where(allow_survey: "true").present?) && (!survey.get_sharable_link)
      false
    elsif !survey.delivery_time.present?
      false
    elsif !survey.persona_summary_display_type.present?
      false
    else
      true
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    authorize nil, :is_account?, policy_class: AccountPolicy

    @per_page = params[:per_page].present? ? params[:per_page] : 10

    @lists = List.where(account_id: $community_account.id, archived: false).paginate(page: params[:page], per_page: @per_page)
  end

  def show
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize @list.account, :can_view?, policy_class: AccountPolicy

    @per_page = params[:per_page].present? ? params[:per_page] : 10

    @list_recipients = @list.recipients.paginate(page: params[:page], per_page: @per_page)
  end

  def new
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize $community_account, :can_add_edit_delete_global?, policy_class: AccountPolicy

    @list = List.new

    respond_to do |format|
      format.js
    end
  end

  def edit
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize $community_account, :can_add_edit_delete_global?, policy_class: AccountPolicy

    respond_to do |format|
      format.js
    end
  end

  def create
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize $community_account, :can_add_edit_delete_global?, policy_class: AccountPolicy

    @list = List.new(list_params)
    @list.account_id = $community_account.id
    @list.created_by_id = current_account.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list
        # , notice: 'List was successfully created.'
        }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize $community_account, :can_add_edit_delete_global?, policy_class: AccountPolicy

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list
        # , notice: 'List was successfully updated.'
        }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize $community_account, :can_add_edit_delete_global?, policy_class: AccountPolicy

    @list.toggle(:archived).save

    respond_to do |format|
      format.html { redirect_to lists_url
      # , notice: 'List was successfully deleted.'
      }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = List.not_deleted.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :account_id, :created_by_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/surveys/categories_surveys_helper.rb
module Surveys::CategoriesSurveysHelper
end

app/views/surveys/categories_surveys/list/_form.html.erb
<%= simple_form_for(@list, url: create_list_survey_categories_surveys_path(params[:survey_id]), :remote => true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="cgroup-form">
    <%= f.label :title, "#{t 'lists.list_name'}" %>
    <%= f.input :title, label: false, placeholder: '', required: false, focus: true, input_html: { required: false, class: 'input-field__input input--big' } %>
    <span class="text-mutued"><%= t 'lists.enter_list_name_here'%>.</span>

    <div class="input input--extra-big multi-emails-box">
      <%= f.label :multi_emails, "#{t 'lists.email_addresses'}" %>
      <%= f.input :multi_emails, as: :text, label: false, required: false, input_html: { class:"input-field__textarea input--extra-big", id:"multi_emails" } %>
      <div class="caption-h2 input-field__caption mt-10"><%=t 'lists.please_enter_email'%>.</div>
    </div>
  </div>

  <%= f.button :submit, @list.new_record? ? "#{t 'lists.create_list'}" : "#{t 'lists.update_list'}", class: 'btn-primary btn-lg px-4 submit start-creating-recp-btn' %>

<% end %>
<script type="text/javascript">
  $('form').on('submit', function () {
      if (($('#list_title').val() == '') && ($('#multi_emails').val() == '')){
          $('#list_title').addClass('input-field--error');
          $('#multi_emails').addClass('input-field--error');
          return false
    }
     if (($('#list_title').val() == '') || ($('#multi_emails').val() == '')){
        if (($('#list_title').val() == '')){
          $('#list_title').addClass('input-field--error');
        }
        if (($('#multi_emails').val() == '')){
          $('#multi_emails').addClass('input-field--error');
        }
        return false
      }
    })
</script>

app/views/surveys/categories_surveys/list/_list_render.html.erb
<div class="checkbox_with_toggler">

  <label class="d-inline-block checkbox-container hide">
    <%= l.title %>
    <input class="checkboxToggle master-list-id-<%= l.id %> exit-check" type="checkbox" value="<%= l.id %>" name="survey[list_ids][]" id="survey_list_ids_<%= l.id %>">
    <span class="checkmark"></span>
  </label>


  <span class="chevron chevron<%= l.id %> fa fa-chevron-down"></span>

  <div class="checkboxDropdown hide">

    <div class="row">
      <div class="col-lg-3">
        <div class="py-3 mb-1">
          <label class="form-check-label">
            <strong><%=t 'surveys.send_to'%>:</strong>
          </label>
        </div>
      </div>

      <div class="col-lg-9">
        <div class="row">
          <div class="col-md-4">
            <div class="form-check py-3 radio-box mb-1">
              <input class="form-check-input" type="radio" id="all<%= l.id %>" name="select_respondents<%= l.id %>" value="all<%= l.id %>">
              <label class="form-check-label" for="all<%= l.id %>">
                <%=t 'surveys.all'%>
              </label>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-check py-3 radio-box mb-1">
              <input class="form-check-input" type="radio" id="selected<%= l.id %>" name="select_respondents<%= l.id %>" value="selected<%= l.id %>" checked>
              <label class="form-check-label" for="selected<%= l.id %>">
                <%=t 'surveys.selected'%>
              </label>
            </div>
          </div>
          <div class="col-md-4">

            <div class="form-check py-3 radio-box mb-1">


              <%= link_to new_recipient_modal_survey_categories_surveys_path(@survey, list_id: l.id), method: :get, remote: true, class: "creating-survey__new-group-link" do %>
                <span class="creating-survey__new-group-icon"></span>
                <%=t 'surveys.add_more'%>
              <% end %>


            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="respondents list<%= l.id %>">


      <div class="row mt-4">
        <div class="col-lg-6">
          <label class="mb-1"> <span class="list-respondents-count<%= l.id %>"><%= l.recipients.count %></span> <%=t 'surveys.respondents'%></label>
        </div>

        <div class="col-lg-6">
          <div class="input-group mb-3 search-group<%= l.id %>">
            <div class="input-group-prepend">
              <span class="input-group-text search-addon"><i class="fa fa-search"></i></span>
            </div>
            <input type="text" class="form-control search-box<%= l.id %>" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1">
          </div>
        </div>
      </div>

      <div class="row mt-3 recipient-render<%= l.id %>">


        <% l.recipients.each_with_index do |r, index| %>
          <% @random_id = SecureRandom.random_number(2391) + index + r.id.to_i + l.id.to_i %>

          <div class="col-md-6" style="">


            <label class="checkbox-container bg-transparent">
              <span class="checkbox-label"><%= r.email %></span>
              <input name="survey[recipients_surveys_attributes][<%= @random_id %>][allow_survey]" type="hidden" value="false"><input class="checkbox list-recipients-<%= l.id %>" type="checkbox" value="true" name="survey[recipients_surveys_attributes][<%= @random_id %>][allow_survey]" id="survey_recipients_surveys_attributes_<%= @random_id %>_allow_survey">
              <span class="checkmark"></span>
            </label>

            <input value="<%= survey.id %>" type="hidden" name="survey[recipients_surveys_attributes][<%= @random_id %>][survey_id]" id="survey_recipients_surveys_attributes_<%= @random_id %>_survey_id">
            <input value="<%= l.id %>" type="hidden" name="survey[recipients_surveys_attributes][<%= @random_id %>][list_id]" id="survey_recipients_surveys_attributes_<%= @random_id %>_list_id">
            <input value="<%= r.id %>" type="hidden" name="survey[recipients_surveys_attributes][<%= @random_id %>][recipient_id]" id="survey_recipients_surveys_attributes_<%= @random_id %>_recipient_id">

          </div>
        <% end %>


      </div>

      <script type="text/javascript" charset="utf-8">

          $('input[name=select_respondents<%= l.id %>]').change(function () {
              respondentsToggle<%= l.id %>(this);
          });

          $('.search-box<%= l.id %>').keyup(function () {
              var search = $(this).val();

              if (search.length > 0) {
                  $('.list<%= l.id %> .checkbox-label').parent().parent().hide();
                  $('.list<%= l.id %> .checkbox-label:contains(' + search + ')').each(function () {
                      $(this).parent().parent().show();
                  });
              } else {
                  $('.list<%= l.id %> .checkbox-label').parent().parent().show();
              }
          });

          $('.clear-list<%= l.id %>').click(function () {
              $('.list<%= l.id %> input').each(function () {
                  $(this).prop('checked', false);
              });

              $(".master-list-id-<%= l.id %>").prop('checked', false);
              $("#selected<%= l.id %>").click();
          });

          $(".master-list-id").click(function () {
              $(".exit-check").each(function () {
              $(this).prop('checked', false);
              $('.list<%= l.id %> input').each(function () {
                      $(this).prop('checked', false);
                  });

                  $("#selected<%= l.id %>").click();
            });
          });

          $('.master-list-id-<%= l.id %>').click(function () {
              if (this.checked) {
                  $('.list<%= l.id %> input').each(function () {
                      $(this).prop('checked', true);
                  });

                  $("#all<%= l.id %>").click();
              } else {
                  $('.list<%= l.id %> input').each(function () {
                      $(this).prop('checked', false);
                  });

                  $("#selected<%= l.id %>").click();
              }
              $(".master-list-id").prop('checked', false);
          });

          // Default call on page load to mark all vs selected
          if ($('input.list-recipients-<%= l.id %>:checked').length == 0 && $('input.list-recipients-<%= l.id %>').length == 0) {
              $("#selected<%= l.id %>").click();
              $(".master-list-id-<%= l.id %>").prop('checked', false);
          } else if ($('input.list-recipients-<%= l.id %>:checked').length == $('input.list-recipients-<%= l.id %>').length) {
              $("#all<%= l.id %>").click();
          } else if ($('input.list-recipients-<%= l.id %>:checked').length == 0) {
              $("#selected<%= l.id %>").click();
              $(".master-list-id-<%= l.id %>").prop('checked', false);
          } else {
              $("#selected<%= l.id %>").click();
              $(".master-list-id-<%= l.id %>").prop('checked', true);
          }

          $('.list-recipients-<%= l.id %>').click(function () {

              if ($('input.list-recipients-<%= l.id %>:checked').length == 0 && $('input.list-recipients-<%= l.id %>').length == 0) {
                  $("#selected<%= l.id %>").click();
                  $(".master-list-id-<%= l.id %>").prop('checked', false);
              } else if ($('input.list-recipients-<%= l.id %>:checked').length == $('input.list-recipients-<%= l.id %>').length) {
                  $("#all<%= l.id %>").click();
              } else if ($('input.list-recipients-<%= l.id %>:checked').length == 0) {
                  $("#selected<%= l.id %>").click();
                  $(".master-list-id-<%= l.id %>").prop('checked', false);
              } else {
                  $("#selected<%= l.id %>").click();
                  $(".master-list-id-<%= l.id %>").prop('checked', true);
              }

          });

          function respondentsToggle<%= l.id %>(selected) {
              if ($(selected).val() == 'all<%= l.id %>') {
                  $(".master-list-id").prop('checked', false);
                  $('.list<%= l.id %> input').each(function () {
                      $(this).prop('checked', true);
                  });
                  $(".master-list-id-<%= l.id %>").prop('checked', true);

              } else {
                  $('.list<%= l.id %> input').each(function () {
                      // $(this).prop('checked', false);
                  });
              }
          }

          $('.checkbox_with_toggler .chevron<%= l.id %>').click(function () {
              $(this).toggleClass('fa-chevron-up fa-chevron-down');
              $(this).siblings('.checkboxDropdown').toggleClass('hide show');
          });

          $('.list-respondents-count<%= l.id %>').text('<%= l.recipients.count %>');
      </script>
    </div>
  </div>
</div>

app/views/surveys/categories_surveys/list/_modal.html.erb
<div class="modal" id="ListAddModal" tabindex="-1" role="dialog" aria-labelledby="ListAddModalLabel">

  <div class="modal-dialog modal-lg modal-dialog-centered cgroup-pop-modal" role="document">
    <div class="modal-content">


      <div class="modal-body">
        <div class="cgroup-pop">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <div class="cgroup-pop-header text-center">
            <div class="cgroup-pop-header-title">
            <%if @list.new_record? %>
              <%="#{t 'lists.create_new_list'}"%>
            <%else%>
              <%="#{t 'lists.update'}" %> <%= t 'lists.list'%>
            <%end%>
           </div>
            <div class="cgroup-pop-header-text" style="width:110%;text-align:left;"><%=t 'lists.your_about_to'%> <%= @list.new_record? ? "#{t 'lists.description_create_new_list'}" : "#{t 'lists.update_list'}" %> <br/> <%t 'lists.list'%> <%=t 'lists.please_give_your'%> <%=t 'lists.list_a_name'%></div>
          </div>

          <%= render 'surveys/categories_surveys/list/form', list: @list %>

        </div>
      </div>

    </div>
  </div>

</div>

<script type="text/javascript" charset="utf-8">
    $('#ListAddModal').modal();



    $('#multi_emails').blur(function() {
        validateMultipleEmails($('#multi_emails').val());
    });

    $('#multi_emails').keypress(function() {
        validateMultipleEmails($('#multi_emails').val());
    });


    function validate(emailInput) {

    }

    function validateMultipleEmails(emailInput) {
        // Get value on emails input as a string
        var emails = emailInput;

        // Split string by comma into an array
        emails = emails.split(",");

        var valid = true;
        var regex = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

        var invalidEmails = [];

        for (var i = 0; i < emails.length; i++) {
            // Trim whitespaces from email address
            emails[i] = emails[i].trim();

            // Check email against our regex to determine if email is valid
            if( emails[i] == "" || ! regex.test(emails[i])){
                invalidEmails.push(emails[i]);
            }
        }

        // Output invalid emails
        $('.multi-emails-box .text-danger').remove();
        $('.start-creating-recp-btn').removeAttr("disabled");

        if(invalidEmails != 0) {
            $('.multi-emails-box').append('<p class="caption-h2 mt-10 text-danger"><%= t 'surveys.invalid_emails'%> ' + invalidEmails.join(', ') + '</p>');
            $(".start-creating-recp-btn").attr("disabled", true);
        }
    }
</script>