config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'  # end

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  devise_for :accounts, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'accounts/omniauth_callbacks'}
  scope "(:locale)" do
    root to: 'dashboard#index'
    resources :personas, only: [:index]

    resources :user_passwords, path: 'user/password'

    get '/get_states', to: 'csc#get_states', as: :get_states
    get '/get_cities', to: 'csc#get_cities', ad: :get_cities

    get 'dashboard/index'
    get 'not_found', to: 'errors#not_found'

    resource :dashboard, controller: 'dashboard' do
      collection do
        get :active
        get :draft
        get :finished
      end
    end


    devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, skip: :omniauth_callbacks

    resources :users, path: 'account/users'
    get 'accept_invitation/:id', to: "users#accept_invitation", as: :accept_invitation

    resources :account_settings, except: [:new, :index, :create, :edit, :update, :destroy] do
      member do
        delete :delete_image_attachment
      end
      collection do
        post :overview_update
        post :settings_update
        post :new_billing_email
        post :update_billing_email
      end
    end

    get 'dashboard/settings'

    match '/account_settings', to: 'account_settings#settings', via: :get
    resources :users do
      member do
        put :update_user
        get :resend_invitation
      end
    end

    scope 'account', as: 'account' do
      resources :users
    end

    scope 'account_settings', as: 'account_settings' do
      resources :users
    end
 
    resources :groups, except: [:show] do
      collection do
        get :choose_template
        get :choose_template_tab
        get :industry_themes
        get :destroy_template
      end

      resources :surveys, controller: 'groups/surveys' do
        member do
          get :results
        end

        collection do
          get :all
          get :finished
          get :active
          get :draft
        end
      end
    end

    resources :customized_personas do
      collection do
        get :export_pdf
      end
    end

    resources :reports do
      resources :surveys, controller: 'reports/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end
    
    resources :results do
      resources :surveys, controller: 'results/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end

    get 'persona_display_type/:display_type_id', to: 'persona_display_types#display_type', as: :persona_display_type

    get 'survey/:survey_token', to: 'survey_submissions#start', as: :public_survey
    post 'survey/continue', to: 'survey_submissions#continue', as: :public_survey_continue
    get 'survey/submit', to: 'survey_submissions#new', as: :public_survey_new

    get 'survey/:survey_token/:encr_mail_id', to: 'survey_submissions#start', as: :encr_mail_survey_open

    post 'survey/screen', to: 'survey_submissions#screen_submit', as: :public_survey_screen

    resources :survey_submissions, except: [:index]

    resources :surveys, controller: 'surveys' do
      member do
        get :success
        get :preview_survey
        get :preview_survey_branching
        get :save_as_a_template
        post :save_as_a_template_create
        get :respondent_with_answers
        get :disable_or_enable_shared_link
      end

      collection do
        get :new_group
        post :create_group

        get :clone
        post :clone_submit

        get :move
        post :move_submit

        get :duplicate
        post :duplicate_submit
      end

      resources :steps, controller: 'surveys/steps'

      resources :categories_surveys, controller: 'surveys/categories_surveys' do
        collection do
          get :new_list_modal
          post :create_list

          get :new_recipient_modal
          post :create_recipient

          get :add_block_modal

          get :remove_custom_block

          get :clone_block_modal
          post :clone_block

          get :save_as_block_modal
          post :save_as_block_submit

          get :edit_block_modal
          patch :edit_block

          get :delete_question

          get :new_question
          post :new_question_submit

          get :duplicate_question

          get :edit_question
          patch :update_question

          get :get_group_by_question_types_templates

          get :reset
        end
      end
    end

    resources :lists do
      resources :recipients
    end


    match '/admin', to: 'admin#dashboard', via: :get
    namespace :admin do

      resources :accounts do
        collection do
          get :activate_or_disable
          get :okta_enable
          get :okta_disable
          post :add_trial_submit
        end
        member do
          get :reinstate
        end
      end

      resources :industries

      resources :template_themes do
        member do
          get :preview
          
          get :clone_template_modal 
          post :clone_template
        end

        resources :steps, controller: 'template_themes/steps' do
          collection do
            get :preview_survey
          end
        end

        resources :template_categories, controller: 'template_themes/categories_template_themes' do
          collection do
            get :preview_survey

            get :add_block_modal

            get :clone_block_modal
            post :clone_block

            get :edit_block_modal
            patch :edit_block

            get :delete_question
            get :edit_question
            patch :update_question

            get :get_group_by_question_types_templates

            get :reset
          end
        end

      end

      resources :categories, path: 'block-templates' do
        member do
          get :preview

          get :clone_block_modal
          post :clone_block
        end
        resources :questions, controller: 'categories/questions'
      end

      resources :label_templates do
        collection do
          get :get_group_by_question_types_templates
          get :get_template_description
        end
      end

    end
  end

end

app/models/survey.rb
class Survey < ApplicationRecord
  # default_scope {order(created_at: :desc)}

  attr_accessor :date_range
  attr_reader :date_range

  # FIXME add sender id to survey who activated survey also check for emails

  # FIXME use enum for survey_types
  # enum survey_type: {"Survey" => 0,
  #                        "" => 1,
  #                        "Persona" => 2}


  belongs_to :template_theme, optional: true
  belongs_to :group
  belongs_to :creator, class_name: 'Account', foreign_key: :created_by_id
  has_and_belongs_to_many :industries
  has_and_belongs_to_many :lists
  has_and_belongs_to_many :recipients
  has_many :categories, dependent: :destroy
  has_many :categories_surveys
  has_many :category_blocks, through: :categories_surveys, source: :category
  has_many :submissions, dependent: :destroy
  has_many :custom_personas, dependent: :destroy

  has_many :recipients_surveys
  has_many :allowed_recipients_surveys, -> { allowed_survey }, class_name: "RecipientsSurvey"

  accepts_nested_attributes_for :recipients_surveys, allow_destroy: true

  scope :undeleted_survey, -> { where("deleted_at IS NULL") }



  def recipients_surveys_for_form(survey_id, list_id, recipient_id)
    collection = recipients_surveys.where(list_id: list_id, recipient_id: recipient_id)
    collection.any? ? collection : recipients_surveys.build
  end

  enum survey_state: {"Draft" => 0,
                         "Active" => 1,
                         "Finished" => 2}

  enum persona_summary_display_types: {"Template 1" => 0, "Template 2" => 1}

  before_create :set_default_value
  after_save :set_delivery_time

  def set_default_value
    survey_token = Digest::SHA1.hexdigest([Time.now, rand].join)
    public_token = Digest::SHA1.hexdigest([Time.now, rand(34534656)].join)
    self.survey_token = survey_token
    self.public_token = public_token
    self.survey_state = 0
  end

  def aggregator
    SubmissionsAggregator.new(submissions: self.submissions,
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def pdf_aggregator submission_ids
    SubmissionsAggregator.new(submissions: self.submissions.where(id: submission_ids),
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def aggregator_scoring
    SubmissionsAggregatorScoring.new(submissions: self.submissions,
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def pdf_aggregator_scoring submission_ids
    SubmissionsAggregatorScoring.new(submissions: self.submissions.where(id: submission_ids),
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def customized_aggregator_scoring(submissions)
    CustomSubmissionsAggregatorScoring.new(submissions: submissions,
                              areas: self.categories_surveys.pluck(:category_id))
  end

  def summary_calculator
    SurveySummaryCalculator.new(submissions: self.submissions, recipients: self.recipients_surveys.where(allow_survey: "true").pluck(:recipient_id).uniq)
  end

  def set_delivery_time
    survey = self
    unless delivery_time.blank?
      # p self.delivery_time.strftime("%Y-%m-%d")+ ' ' + @record.date_time.to_datetime.strftime('%H:%M:%S')
      unless self.delivery_start_at.blank?
        delivery_period = self.delivery_start_at.localtime.strftime("%Y-%m-%d")+ ' ' + self.delivery_time.localtime.strftime('%H:%M:%S') 
        self.update_column(:delivery_time, delivery_period)
      end
 
    end
  end

  def self.all_step_valid_survey(survey)
    if !survey.title.present?
      false
    elsif !survey.welcome_page.present?
      false
    elsif (!survey.lists.present? || !survey.recipients_surveys.where(allow_survey: "true").present?) && (!survey.get_sharable_link)
      false
    elsif !survey.delivery_time.present?
      false
    elsif !survey.persona_summary_display_type.present?
      false
    else
      true
    end
  end

end

app/helpers/groups/surveys_helper.rb
module Groups::SurveysHelper
end

app/helpers/surveys/categories_surveys_helper.rb
module Surveys::CategoriesSurveysHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper

  def set_survey_steps
      ['setup', 'build', 'respondents', 'display_type', 'deliver']
  end

  def all_step_valid_survey(survey)
    if !survey.title.present?
      false
    elsif !survey.welcome_page.present?
      false
    elsif (!survey.lists.present? || !survey.recipients_surveys.where(allow_survey: "true").present?) && (!survey.get_sharable_link)
      false
    elsif !survey.delivery_time.present?
      false
    elsif !survey.persona_summary_display_type.present?
      false
    else
      true
    end
  end

  def first_invalid_step_survey(survey)
    if !survey.title.present?
      'setup'
    elsif !survey.welcome_page.present?
      'build'
    elsif !survey.lists.present? || !survey.recipients_surveys.where(allow_survey: "true").present?
      'respondents'
    elsif !survey.persona_summary_display_type.present?
      'display_type'
    elsif !survey.delivery_time.present?
      'deliver'
    else
      ''
    end
  end

  def active_or_done_survey(template, step, current_step)
    if set_survey_steps.first == step
      if template.title.present? and current_step == step
        'wizard__item--done-v1'
      elsif template.title.present? and current_step != step
        'wizard__item--done'
      elsif !template.title.present? and current_step != step
        ''
      end

    elsif set_survey_steps.second == step
      if template.welcome_page.present? and current_step == step
        'wizard__item--done-v1'
      elsif template.welcome_page.present? and current_step != step
        'wizard__item--done'
      elsif !template.welcome_page.present? and current_step == step
        ''
      end

    elsif set_survey_steps.third == step
      if template.lists.present? and template.recipients_surveys.where(allow_survey: "true").present? and current_step == step
        'wizard__item--done-v1'
      elsif template.lists.present? and template.recipients_surveys.where(allow_survey: "true").present? and current_step != step
        'wizard__item--done'
      elsif template.get_sharable_link == true && current_step != step
        'wizard__item--done'
      elsif template.get_sharable_link == true && current_step == step
        'wizard__item--done-v1'
      elsif !template.lists.present? and current_step == step
        ''
      end

    elsif set_survey_steps.fourth == step
      if template.persona_summary_display_type.present? and current_step == step
        'wizard__item--done-v1'
      elsif template.persona_summary_display_type.present? and current_step != step
        'wizard__item--done'
      elsif !template.persona_summary_display_type.present? and current_step == step
        ''
      end

    elsif set_survey_steps.fifth == step
      if template.delivery_time.present? and current_step == step
        'wizard__item--done-v1'
      elsif template.delivery_time.present? and current_step != step
        'wizard__item--done'
      elsif !template.delivery_time.present? and current_step == step
        ''
      end
    end
  end

  def active_or_done_mobile_survey(template, step, current_step)
    if set_survey_steps.first == step
      if template.title.present? and current_step == step
        'active yellow-btn'
      elsif template.title.present? and current_step != step
        'yellow-btn'
      elsif !template.title.present? and current_step == step
        'active'
      end

    elsif set_survey_steps.second == step
      if template.welcome_page.present? and current_step == step
        'active yellow-btn'
      elsif template.welcome_page.present? and current_step != step
        'yellow-btn'
      elsif !template.welcome_page.present? and current_step == step
        'active'
      end

    elsif set_survey_steps.third == step
      if template.lists.present? and template.recipients_surveys.where(allow_survey: "true").present? and current_step == step
        'active yellow-btn'
      elsif template.lists.present? and template.recipients_surveys.where(allow_survey: "true").present? and current_step != step
        'yellow-btn'
      elsif !template.lists.present? and current_step == step
        'active'
      end

    elsif set_survey_steps.fourth == step
      if template.persona_summary_display_type.present? and current_step == step
        'active yellow-btn'
      elsif template.persona_summary_display_type.present? and current_step != step
        'yellow-btn'
      elsif !template.persona_summary_display_type.present? and current_step == step
        'active'
      end

    elsif set_survey_steps.fifth == step
      if template.delivery_time.present? and current_step == step
        'active yellow-btn'
      elsif template.delivery_time.present? and current_step != step
        'yellow-btn'
      elsif !template.delivery_time.present? and current_step == step
        'active'
      end
    end
  end

  def sender_from_title
    if $community_account.company_name.present?
      $community_account.company_name
    else
      $community_account.your_name
    end
  end

  def sender_emails
    if $community_account.company_name.present?
      [$community_account.company_email]
    else
      [$community_account.sender_email]
    end
  end

end

app/views/surveys/_form.html.erb
<div class="content-wrapper">
  <%= render partial: 'surveys/shared/tablist', locals: {survey_type: params[:survey_type]}%>

  <main class="content content--side-short creating-survey">

    <div class="creating-survey__navigation">
      <div class="creating-survey__step-wrapper">
        <span class="creating-survey__step-info fnt-16"><%= t 'surveys.setup'%></span>
        <small class="creating-survey__step-number fnt-16"><%= t 'surveys.step'%> 1/<%= set_survey_steps.count %></small>
      </div>

      <div class="creating-survey__button-wrapper">
        <a href="#" class="creating-survey__link creating-survey__link--large fnt-16" onClick='$("button[type=submit]").click()'><%= t 'surveys.save_and_exit'%></a>

        <% if params[:group_id].present? %>
          <%= link_to "#{t 'surveys.exit'}", all_group_surveys_path(params[:group_id]), class: 'creating-survey__link creating-survey__link--large fnt-16' %>
        <% else %>
          <%= link_to "#{t 'surveys.exit'}", groups_path, class: 'creating-survey__link creating-survey__link--large fnt-16' %>
        <% end %>
        <ul class="navbar-nav navbar-right" style="float: right; margin-left: 12px; font-size: 16px;">
          <li class="nav-item dropdown">
            <a class="d-inline-block v-middle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%=(I18n.locale.to_s == "fr_ca") ? "FR" : "EN" %>
            <p class="fa fa-chevron-down v-middle" aria-hidden="true"></p>
            </a>
            <div class="dropdown-menu hi" aria-labelledby="navbarDropdown" style="margin-left:-100px;" >
              <%= link_to "#{t 'dashboard.english'}", url_for(locale: :en, template_id: params[:template_id], group_id: params[:group_id]), class: "dropdown-item" %>
              <%= link_to "#{t 'dashboard.french'}", url_for(locale: :fr_ca, template_id: params[:template_id], group_id: params[:group_id]), class: "dropdown-item" %>
            </div>

          </li>
        </ul>
      </div>
    </div>

    <%= render partial: 'surveys/shared/mobile_tablist' , locals: {survey_type: params[:survey_type]}%>

    <div class="creating-survey__content">
      <%= simple_form_for(@survey, url: (@survey.new_record? ? surveys_path : survey_path), html: {class: 'creating-survey__form'}) do |form| %>

        <%if params[:build_own] != "true"%>
          <%= form.hidden_field :template_theme_id, value: @template_theme.id %>
        <%end%>
        <%= form.hidden_field :build_own, value: params[:build_own] %>
        <%= form.hidden_field :survey_type, value: params[:survey_type] %>
        
        <fieldset class="creating-survey__fieldset">
          <legend class="creating-survey__legend"> <%=t 'surveys.survey_info'%> </legend>

            <div class="input input-field input--email creating-survey__input">
              <%if params[:survey_type].present? && params[:survey_type].to_s == "persona"%>
                <label for="survey_title" class="input-field__label--email"><%=t 'personas.persona_title'%> *</label>
              <%else%>
                <label for="survey_title" class="input-field__label--email"><%=t 'surveys.survey_title'%> *</label>
              <%end%>
              <%= form.text_field :title, class: 'input-field__input input--big', label: false, value: params[:build_own] != "true" ? @template_theme.title : "", placeholder: 'eg: Customer Satisfaction', focus: true %>
              <%if params[:survey_type].present? && params[:survey_type].to_s == "persona"%>
                <small class="input-field__echo--email"><%=t 'personas.give_your_persona_title'%></small>
              <%else%>
                <small class="input-field__echo--email"><%=t 'surveys.give_your_survey_title'%></small>
              <%end%>
            </div>

          <!-- <div class="creating-survey__input input--medium">
            <label for="survey_industry_ids" class="input-field__label--email" style="line-height: 35px;"><%#=t 'surveys.industry_type'%> *</label>
            <%#= form.association :industries, label: false %>
            <small class="input-field__echo--email"><%#=t 'surveys.add_one_related_industries'%></small> -->
          <!-- </div> -->
          <%=form.hidden_field :industry_ids, :multiple => true, value: params[:industary_id]%>

          <div class="creating-survey__input input--medium group-render">
            <label for="survey_group_id" class="input-field__label--email" style="line-height: 35px;"><%=t 'surveys.group'%> *</label>
            <%= form.select :group_id, options_for_select($community_account.groups.where(archived: false).pluck(:title, :id), params[:group_id].present? ? params[:group_id] : form.object.group_id), {:include_blank => true, :label => false}, {:required => false} %>
            <small id="survey_group_desc" class="input-field__echo--email"><%=t 'surveys.add_your_survey_to_group'%></small>
          </div>

          <div class="creating-survey__new-group">
            <a href="#" class="creating-survey__new-group-link create-group-service"><span class="creating-survey__new-group-icon"></span><%=t 'surveys.create_new_group'%></a>
          </div>

        </fieldset>

        <br>
        <br>

        <fieldset class="creating-survey__fieldset">
          <legend class="creating-survey__legend"><%=t 'surveys.email_info'%></legend>

          <div class="input input-field input--email creating-survey__input">
            <%= form.label :email_from, "#{t 'surveys.from_name'} *", class:"input-field__label--email" %>
            <%= form.input :email_from, as: :string, label: false, input_html: { value: sender_from_title, class:'input-field__input input--medium' } %>
            <small id="email_from_desc" class="input-field__echo--email"><%=t 'surveys.name_of_email_sender'%></small>
          </div>

          <div class="creating-survey__input input--medium">
            <%= form.label :email_sender, "#{t 'surveys.from_email_address'} *", class:"input-field__label--email" %>
            <%= form.select :email_sender, options_for_select(sender_emails), label: false %>
            <small id="email_name_desc" class="input-field__echo--email"><%=t 'surveys.email_that_survey_will_sent'%></small>
          </div>

          <div class="input input-field input--email creating-survey__input">
            <%= form.label :email_subject, "#{t 'surveys.email_subject_line'} *", class:"input-field__label--email" %>
            <%= form.input :email_subject, as: :string, label: false, input_html: { class:'input-field__input input--extra-big', placeholder:"#{t 'surveys.placeholder_survey'}" } %>
            <small id="email_desc" class="input-field__echo--email"><%=t 'surveys.email_subject_shown'%></small>
          </div>

        </fieldset>

        <div class="creating-survey__button">
          <%= button_tag(type: 'submit', class: "btn btn-primarybtn btn--primary-icon btn--medium-primary-icon save-and-exit") do %>
            <%=t 'surveys.save_and_continue'%><span class="icon-wide-right-small"></span>
          <% end %>
        </div>

      <% end %>
    </div>
  </main>
</div>

<script>
    $('form').submit(function(){
        // $(this).find('button[type=submit]').prop('disabled', true);
      if (($('#survey_title').val() == '') && ($('#survey_email_from').val() == '') && ($('#survey_email_subject').val() == '') && ($('#survey_group_id').val() == '') && ($('#survey_email_sender').val() == null)){
        $('#survey_title').addClass('input-field--error');
        $('#survey_email_from').addClass('input-field--error');
        $('#survey_email_subject').addClass('input-field--error');
        // $('.sumo_survey[industry_ids]').addClass('input-field--error');
        $('.SumoSelect').eq(0).addClass('input-field--error')
        // $('#survey_industry_ids').next().addClass('input-field--error')
        //$('.SumoSelect').eq(1).addClass('input-field--error')
        $('#survey_group_id').next().addClass('input-field--error')
        //$('.SumoSelect').eq(2).addClass('input-field--error')
        $('#survey_email_sender').next().addClass('input-field--error')

        return false
      }
      if (($('#survey_title').val() == '') || ($('#survey_email_from').val() == '') || ($('#survey_email_subject').val() == '') || ($('#survey_group_id').val() == '') || ($('#survey_email_sender').val() == null)){
        if ($('#survey_title').val() == ''){
          $('#survey_title').addClass('input-field--error');
        }
        // if ($('#survey_industry_ids').val() == null) {
        //   $('.SumoSelect').eq(0).addClass('input-field--error')
        //   $('#survey_industry_ids').next().addClass('input-field--error')
        // }
        if ($('#survey_group_id').val() == '') {
          //$('.SumoSelect').eq(1).addClass('input-field--error')
          $('#survey_group_id').next().addClass('input-field--error')
        }
        if ($('#survey_email_sender').val() == null) {
          //$('.SumoSelect').eq(2).addClass('input-field--error')
          $('#survey_email_sender').next().addClass('input-field--error')
        }
        if ($('#survey_email_from').val() == ''){
          $('#survey_email_from').addClass('input-field--error');
        }
        if ($('#survey_email_subject').val() == ''){
          $('#survey_email_subject').addClass('input-field--error');
        }
        return false
      }
    });


    $('#survey_title').blur(function() {
        if ($('#survey_title').val() == ''){
          $('#survey_title').addClass('input-field--error');
        }
        else{
          $('#survey_title').removeClass('input-field--error');
        }
    });

    $('#survey_title').keypress(function() {
       if ($('#survey_title').val() == ''){
          $('#survey_title').addClass('input-field--error');
        }
        else{
          $('#survey_title').removeClass('input-field--error');
        }
    });

    $('#survey_email_from').blur(function() {
        if ($('#survey_email_from').val() == ''){
          $('#survey_email_from').addClass('input-field--error');
        }
        else{
          $('#survey_email_from').removeClass('input-field--error');
        }
    });

    $('#survey_email_from').keypress(function() {
       if ($('#survey_email_from').val() == ''){
          $('#survey_email_from').addClass('input-field--error');
        }
        else{
          $('#survey_email_from').removeClass('input-field--error');
        }
    });

    $('#survey_email_subject').blur(function() {
        if ($('#survey_email_subject').val() == ''){
          $('#survey_email_subject').addClass('input-field--error');
        }
        else{
          $('#survey_email_subject').removeClass('input-field--error');
        }
    });

    $('#survey_email_subject').keypress(function() {
       if ($('#survey_email_subject').val() == ''){
          $('#survey_email_subject').addClass('input-field--error');
        }
        else{
          $("#email_desc").addClass('field__echo--email').removeClass('validation_description_text_color');	
          $('#survey_email_subject').removeClass('input-field--error');
        }
    });
    
    $('#survey_email_subject').keyup(function(e){if(e.keyCode == 8)
	  if ($('#survey_email_subject').val() == ''){
	  	$("#email_desc").removeClass('field__echo--email').addClass('validation_description_text_color');
	  	$('#survey_email_subject').addClass('input-field--error');
	  }
	})  

    $('#survey_industry_ids').SumoSelect({ search: true, searchText: "<%=t 'surveys.search_and_select_industries'%>", selectAll: true, placeholder: "<%=t 'surveys.select_one_more'%>" });
    $('#survey_group_id').SumoSelect({ search: true, searchText: "<%=t 'surveys.search_and_select_groups' %>", placeholder: "<%=t 'surveys.select_one' %>" });
    $('#survey_email_sender').SumoSelect({ search: true, searchText: "<%=t 'surveys.search_and_select_email'%>", placeholder: "<%=t 'surveys.select_one' %>" });



    $('.create-group-service').click(function (event) {
        $.ajax({
            url: "<%= new_group_surveys_url %>",
            type: "get",
            dataType: 'script',
            success: function (data) {
            }
        });
    });
    
    $(".optWrapper").click(function(){
    	if ($('#survey_group_id').val() != ''){
    		$(".CaptionCont").removeClass('input-field--error').addClass('setup_remove_validation');
    	 $("#survey_group_desc").removeClass('validation_description_text_color').addClass('field__echo--email');	
    	}
    	else
    	{
        var parent_class = $(this).parent().attr('class')
    	if (parent_class == null) {
    	  $(".CaptionCont").removeClass('setup_remove_validation').addClass('input-field--error');
    	}
        }
    });
    
    $(".save-and-exit").click(function(){
      var set_up_email = $('#survey_email_sender').val()
      if (set_up_email == ''){
      	$('.SumoSelect').removeClass('setup_remove_email_validation').addClass('input-field--error')
      } 
      else{
      	$('.SumoSelect').removeClass('input-field--error').addClass('setup_remove_email_validation')
      }	
    });
    $(".save-and-exit").click(function(){
    	if ( $('#survey_email_subject').val() == '' ){
    	  $("#email_desc").removeClass('field__echo--email').addClass('validation_description_text_color');
    	}
    	if ($('#survey_group_id').val() != ''){
    	  //$("#survey_group_desc").removeClass('field__echo--email').addClass('validation_description_text_color');
    	}
    	else{
    		$("#survey_group_desc").removeClass('field__echo--email').addClass('validation_description_text_color');
    	}
    	
    });
</script>

app/views/surveys/clone.js.erb
$('.modal-render').html('<%=j render :partial => "surveys/clone/modal" %>')

app/views/surveys/clone_submit.js.erb
$('#SurveyCloneModal').modal('toggle');
$('#flash').html('<%=j render :partial => "layouts/js_flash_messages" %>');
<%if @from_loc.present?%>
	<%if @from_loc == "dashboard_all"%> 
	    $('#dashboard_all_count').html('<%=j render :partial => "dashboard/dashboard_all_count", locals: {all_surveys: @all_surveys, active_surveys: @active_surveys, finished_surveys: @finished_surveys, draft_surveys: @draft_surveys, all_surveys_count: @all_surveys_count} %>'); 
	    $('#dashboard_all').html('<%=j render :partial => "dashboard/dashboard_all", locals: {all_surveys: @all_surveys,screen_type: "dashboard"} %>');
	  <%else%>
	    $('#all_info_count').html('<%=j render :partial => "groups/surveys/all_info_count", locals: { group: @group, all_surveys: @all_surveys, active_surveys: @active_surveys, finished_surveys: @finished_surveys, draft_surveys: @draft_surveys, all_surveys_count: @all_surveys_count} %>');
	    $('#all_info').html('<%=j render :partial => "groups/surveys/all_info", locals: { group: @group, all_surveys: @all_surveys, active_surveys: @active_surveys, finished_surveys: @finished_surveys, draft_surveys: @draft_surveys} %>');
	<%end%>
<%end%>

app/views/surveys/duplicate.js.erb
$('.modal-render').html('<%=j render :partial => "surveys/duplicate/modal" %>')

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

app/views/surveys/new_group.js.erb
$('.modal-render').html('<%=j render :partial => "surveys/groups/modal" %>')

app/views/surveys/respondent_with_answers.js.erb
$('.modal-render').html('<%=j render :partial => "respondent_with_asnwers_modal" %>');

app/views/surveys/save_as_a_template_create.js.erb
$(".slide-bar, .overlay").removeClass("active");
$(".slide-bar").hide();