config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'  # end

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  devise_for :accounts, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'accounts/omniauth_callbacks'}
  scope "(:locale)" do
    root to: 'dashboard#index'
    resources :personas, only: [:index]

    resources :user_passwords, path: 'user/password'

    get '/get_states', to: 'csc#get_states', as: :get_states
    get '/get_cities', to: 'csc#get_cities', ad: :get_cities

    get 'dashboard/index'
    get 'not_found', to: 'errors#not_found'

    resource :dashboard, controller: 'dashboard' do
      collection do
        get :active
        get :draft
        get :finished
      end
    end


    devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, skip: :omniauth_callbacks

    resources :users, path: 'account/users'
    get 'accept_invitation/:id', to: "users#accept_invitation", as: :accept_invitation

    resources :account_settings, except: [:new, :index, :create, :edit, :update, :destroy] do
      member do
        delete :delete_image_attachment
      end
      collection do
        post :overview_update
        post :settings_update
        post :new_billing_email
        post :update_billing_email
      end
    end

    get 'dashboard/settings'

    match '/account_settings', to: 'account_settings#settings', via: :get
    resources :users do
      member do
        put :update_user
        get :resend_invitation
      end
    end

    scope 'account', as: 'account' do
      resources :users
    end

    scope 'account_settings', as: 'account_settings' do
      resources :users
    end
 
    resources :groups, except: [:show] do
      collection do
        get :choose_template
        get :choose_template_tab
        get :industry_themes
        get :destroy_template
      end

      resources :surveys, controller: 'groups/surveys' do
        member do
          get :results
        end

        collection do
          get :all
          get :finished
          get :active
          get :draft
        end
      end
    end

    resources :customized_personas do
      collection do
        get :export_pdf
      end
    end

    resources :reports do
      resources :surveys, controller: 'reports/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end
    
    resources :results do
      resources :surveys, controller: 'results/surveys' do
        member do
          get :results
          get :respondent_with_answers
          get :export_pdf
          get :export_summary_pdf
        end

        collection do
          get :all
          get :finished
          get :active
        end
      end

      collection do
        get :disable_public_link
        get :generate_public_link
      end
    end

    get 'persona_display_type/:display_type_id', to: 'persona_display_types#display_type', as: :persona_display_type

    get 'survey/:survey_token', to: 'survey_submissions#start', as: :public_survey
    post 'survey/continue', to: 'survey_submissions#continue', as: :public_survey_continue
    get 'survey/submit', to: 'survey_submissions#new', as: :public_survey_new

    get 'survey/:survey_token/:encr_mail_id', to: 'survey_submissions#start', as: :encr_mail_survey_open

    post 'survey/screen', to: 'survey_submissions#screen_submit', as: :public_survey_screen

    resources :survey_submissions, except: [:index]

    resources :surveys, controller: 'surveys' do
      member do
        get :success
        get :preview_survey
        get :preview_survey_branching
        get :save_as_a_template
        post :save_as_a_template_create
        get :respondent_with_answers
        get :disable_or_enable_shared_link
      end

      collection do
        get :new_group
        post :create_group

        get :clone
        post :clone_submit

        get :move
        post :move_submit

        get :duplicate
        post :duplicate_submit
      end

      resources :steps, controller: 'surveys/steps'

      resources :categories_surveys, controller: 'surveys/categories_surveys' do
        collection do
          get :new_list_modal
          post :create_list

          get :new_recipient_modal
          post :create_recipient

          get :add_block_modal

          get :remove_custom_block

          get :clone_block_modal
          post :clone_block

          get :save_as_block_modal
          post :save_as_block_submit

          get :edit_block_modal
          patch :edit_block

          get :delete_question

          get :new_question
          post :new_question_submit

          get :duplicate_question

          get :edit_question
          patch :update_question

          get :get_group_by_question_types_templates

          get :reset
        end
      end
    end

    resources :lists do
      resources :recipients
    end


    match '/admin', to: 'admin#dashboard', via: :get
    namespace :admin do

      resources :accounts do
        collection do
          get :activate_or_disable
          get :okta_enable
          get :okta_disable
          post :add_trial_submit
        end
        member do
          get :reinstate
        end
      end

      resources :industries

      resources :template_themes do
        member do
          get :preview
          
          get :clone_template_modal 
          post :clone_template
        end

        resources :steps, controller: 'template_themes/steps' do
          collection do
            get :preview_survey
          end
        end

        resources :template_categories, controller: 'template_themes/categories_template_themes' do
          collection do
            get :preview_survey

            get :add_block_modal

            get :clone_block_modal
            post :clone_block

            get :edit_block_modal
            patch :edit_block

            get :delete_question
            get :edit_question
            patch :update_question

            get :get_group_by_question_types_templates

            get :reset
          end
        end

      end

      resources :categories, path: 'block-templates' do
        member do
          get :preview

          get :clone_block_modal
          post :clone_block
        end
        resources :questions, controller: 'categories/questions'
      end

      resources :label_templates do
        collection do
          get :get_group_by_question_types_templates
          get :get_template_description
        end
      end

    end
  end

end

app/controllers/reports/surveys_controller.rb
class Reports::SurveysController < ApplicationController
  require 'will_paginate/array'
  before_action :set_group
  before_action :set_survey, only: [:results, :respondent_with_answers]

  def all
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize @group.account, :can_view?, policy_class: AccountPolicy
    
    @per_page = params[:per_page].present? ? params[:per_page] : 10

    surveys = @group.surveys.undeleted_survey.where.not(survey_state: 0).order(created_at: :desc)

    @all_surveys = surveys
    @active_surveys = surveys.select {|survey| survey if active_survey_groups(survey)}
    @finished_surveys = surveys.select {|survey| survey if finished_survey_groups(survey)}
    @all_surveys_count = @all_surveys.to_a.size
    @all_surveys = @all_surveys.paginate(:page => params[:page], per_page: @per_page)

  end

  def active
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize @group.account, :can_view?, policy_class: AccountPolicy

    @per_page = params[:per_page].present? ? params[:per_page] : 10

    surveys = @group.surveys.undeleted_survey.where.not(survey_state: 0).order(created_at: :desc)

    @all_surveys = surveys
    @active_surveys = surveys.select {|survey| survey if active_survey_groups(survey)}
    @finished_surveys = surveys.select {|survey| survey if finished_survey_groups(survey)}
    @active_surveys_count = @active_surveys.to_a.size
    @active_surveys = @active_surveys.paginate(:page => params[:page], :per_page => @per_page)
  end

  def finished
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize @group.account, :can_view?, policy_class: AccountPolicy
    @per_page = params[:per_page].present? ? params[:per_page] : 10

    surveys = @group.surveys.undeleted_survey.where.not(survey_state: 0).order(created_at: :desc)

    @all_surveys = surveys
    @active_surveys = surveys.select {|survey| survey if active_survey_groups(survey)}
    @finished_surveys = surveys.select {|survey| survey if finished_survey_groups(survey)}
    @finished_surveys_count = @finished_surveys.to_a.size
    @finished_surveys = @finished_surveys.paginate(:page => params[:page], :per_page => @per_page)
  end

  def results
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize @survey.group.account, :can_view?, policy_class: AccountPolicy
    @locale = params[:locale]
    @per_page = params[:per_page].present? ? params[:per_page] : 10
    @p_page = params[:p_page].present? ? params[:p_page] : 1
    @c_page = params[:c_page].present? ? params[:c_page] : 1

    @sort_question = @survey.categories_surveys.includes(category: [:questions]).collect{|c| c.category.questions.find_by(sort_results: true)}.reject(&:blank?).take(1).first
    if @sort_question.present?

        @sortable_options = @sort_question.question_labels.select(:id,:label)

      @survey_ans = @survey.aggregator_scoring.result["recipients"][@sort_question.category.id.to_s][@sort_question.id.to_s] 
      @sorted_recipients = {}
      @sortable_options.each do |option|
        label = option.label
        @sorted_recipients[label.to_s] = @survey_ans.to_h.map{ |m|  m[1].key([option.label])}.reject(&:blank?)
      end
      if @sort_question.other_specify == "Yes"
        o_ids = []
        e_options = @sortable_options.pluck(:label)
        @survey_ans.to_h.map{ |m|  m[1].each{ |l, v|
            if v.include?("other")  
             o_ids << l
            else
              o_ids << l if  (v - e_options).present?
            end 
          }
        }.reject(&:blank?)
        @sorted_recipients["other".to_s] = o_ids
      end
    end
    @survey_submissions = @survey.submissions.allowed
    @survey_submissions_count = @survey_submissions.to_a.size
    @survey_submissions_screened_count = @survey.submissions.notallowed.to_a.size
    @survey_submissions = @survey_submissions.paginate(:page => @p_page, :per_page => @per_page)
    @survey_custom_personas = @survey.custom_personas
    @survey_custom_personas_count = @survey.custom_personas.to_a.size
    @survey_custom_personas = @survey_custom_personas.paginate(:page => @c_page, :per_page => @per_page)
    
    @submissions_array = []
    @all_sus = []
    @grade = []
    @adjective = []
    @acceptable = []
    @percentile = []
    
    @submission = @survey_submissions
    @submission.each do |submission|
      @survey_sub = submission.survey
      @survey_sub.categories_surveys.each do |cat_sur|
        @category = cat_sur.category
        if @category && @category.display_type == "system_usability_scale"
          @submissions_array << submission.data_json["data"]["#{cat_sur.category_id}"]
        end
      end
    end
    @submissions_array = @submissions_array.compact

    if @submissions_array.size != 0
      @survey_hash_1 = Hash.new{|h,k| h[k] = [] }
      @answer_array = ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]
      ques_count = @submissions_array.first.length

      @submissions_array.each_with_index do |sub_ary, index|
        for i in 0..(ques_count-1)
          new_idx = i + 1
          @survey_hash_1[index] << (@answer_array.find_index(@submissions_array[index].values[i]) + 1) if @answer_array.find_index(@submissions_array[index].values[i]).present?
        end
      end

      if @survey_hash_1.length != 0
        @sus_cal_1 = {}
        @survey_hash_1.each{ |key, val|
          @a = []
          val.each.with_index(1) do |v, i|
            if i.even?
              @a << 5 - v
            else
              @a << v - 1
            end
          end

          sus = ( (@a.inject(0) { |sum, x| sum + x }) ) * 2.5
          @all_sus << sus
        }
        
        @avg_sus = (@all_sus.inject(0) { |sum, x| sum + x } / @all_sus.size).round(2)

        if (@avg_sus <= 51.6)
          @grade << "F"
        elsif ((51.7 <= @avg_sus) && (@avg_sus <= 62.6))
          @grade << "D"
        elsif ((62.7 <= @avg_sus) && (@avg_sus <= 72.5))
          @grade << "C"
        elsif ((72.6 <= @avg_sus) && (@avg_sus <= 78.8))
          @grade << "B"
        elsif ((78.9 <= @avg_sus) && (@avg_sus <= 100))
          @grade << "A"
        end

        if @avg_sus <= 25
          @adjective << "Worst Imaginable"
        elsif (25.1 <= @avg_sus && @avg_sus <= 51.6)
          @adjective << "Poor"
        elsif (51.7 <= @avg_sus && @avg_sus <= 62.6)
          @adjective << "OK"
        elsif (62.7 <= @avg_sus && @avg_sus <= 72.5)
          @adjective << "Good"
        elsif (72.6 <= @avg_sus && @avg_sus <= 84.0)
          @adjective << "Excellent"
        elsif (84.1 <= @avg_sus && @avg_sus <= 100)
          @adjective << "Best Imaginable"
        end

        if @avg_sus <= 51.6
          @acceptable << "Not Acceptable"
        elsif (51.7 <= @avg_sus && @avg_sus <= 71.0)
          @acceptable << "Marginal"
        elsif (71.1 <= @avg_sus && @avg_sus <= 100)
          @acceptable << "Acceptable"
        end

        if @avg_sus <= 25
          @percentile = 1.9
        elsif (25.1 <= @avg_sus && @avg_sus <= 51.6)
          @percentile = 14
        elsif (51.7 <= @avg_sus && @avg_sus <= 62.6)
          @percentile = 34
        elsif (62.7 <= @avg_sus && @avg_sus <= 64.9)
          @percentile = 40
        elsif (65.0 <= @avg_sus && @avg_sus <= 71.0)
          @percentile = 59
        elsif (71.1 <= @avg_sus && @avg_sus <= 72.5)
          @percentile = 64
        elsif (72.6 <= @avg_sus && @avg_sus <= 74.0)
          @percentile = 69
        elsif (74.1 <= @avg_sus && @avg_sus <= 77.1)
          @percentile = 79
        elsif (77.2 <= @avg_sus && @avg_sus <= 78.8)
          @percentile = 84
        elsif (78.9 <= @avg_sus && @avg_sus <= 80.7)
          @percentile = 89
        elsif (80.8 <= @avg_sus && @avg_sus <= 84.0)
          @percentile = 95
        elsif (84.1 <= @avg_sus && @avg_sus <= 100)
          @percentile = 100
        end

        @grade = @grade.uniq
        @adjective = @adjective.uniq
        @acceptable = @acceptable.uniq
      end
    else
      @avg_sus = 0
      @percentile = 0
    end
  end

  def respondent_with_answers
    authorize nil, :is_account?, policy_class: AccountPolicy
    authorize @survey.group.account, :can_view?, policy_class: AccountPolicy

    @recipients_results = @survey.submissions.present? ? @survey.aggregator_scoring.result["recipients"].freeze : nil
    @survey_submissions = @survey.submissions.allowed

    @submissions_array = []
    @all_sus = []
    @grade = []
    @adjective = []
    @acceptable = []
    @percentile = []
    @show_hide_sus_btn = "show"
    
    @submission = Submission.where(id: params[:submission_id])
    @submission.each do |submission|
      @survey_sub = submission.survey
      @survey_sub.categories_surveys.each do |cat_sur|
        @category = cat_sur.category
        if @category && @category.display_type == "system_usability_scale"
          @submissions_array << submission.data_json["data"]["#{cat_sur.category_id}"]
        end
      end
    end
    @submissions_array = @submissions_array.compact

    if @submissions_array.size != 0
      @survey_hash_1 = Hash.new{|h,k| h[k] = [] }
      @answer_array = ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]
      ques_count = @submissions_array.first.length

      @submissions_array.each_with_index do |sub_ary, index|
        for i in 0..(ques_count-1)
          new_idx = i + 1
          @survey_hash_1[index] << (@answer_array.find_index(@submissions_array[index].values[i]) + 1) if @answer_array.find_index(@submissions_array[index].values[i]).present?
        end
      end

      if @survey_hash_1.length != 0
        @sus_cal_1 = {}
        @survey_hash_1.each{ |key, val|
          @a = []
          val.each.with_index(1) do |v, i|
            if i.even?
              @a << 5 - v
            else
              @a << v - 1
            end
          end

          sus = ( (@a.inject(0) { |sum, x| sum + x }) ) * 2.5
          @all_sus << sus
        }
        

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/disable_public_link.js.erb
$('.survey-public-link').html('<%=j render :partial => "survey_results/info_tab/survey_public_link" %>')

app/views/reports/generate_public_link.js.erb
$('.survey-public-link').html('<%=j render :partial => "survey_results/info_tab/survey_public_link" %>')

app/views/reports/index.html.erb
<style type="text/css">
  .create_dropdown > .dropdown-menu{
    border: none !important;
  }
  .btn--create{
    padding: 0 6rem !important;
  }
</style>
<div class="sub-header">
  <div class="row ml-0 mr-0">
    <div class="col-lg-6">
      <div class="action-bar__body action-bar__body--v1">
        <h3 class="action-bar__heading action-bar__heading--v1 display-h3"><%=t 'reports.results'%></h3>
        <h3 class="action-bar__sub-heading display-h3"><%= @groups.count %> <span class="icon-search"></span></h3>
      </div>
    </div>
    <div class="col-lg-6">
      <% if policy($community_account).can_add_edit_delete_global? %>
        <%#= button_to "#{t 'reports.create_new_survey'}", choose_template_groups_path(group_id: ""), method: :get, remote: true, class: "btn btn-action-bar--v1 btn--big-primary pull-right" %>
        <div class="dropdown create_dropdown pull-right">
          <button class="btn btn--create btn-action-bar--v1 btn--big-primary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%=t 'dashboard.main_create'%>
          </button>
          <div class="dropdown--btn dropdown-menu border-bottom" aria-labelledby="dropdownMenuButton">
            <%= link_to choose_template_groups_path(group_id: "", type: "persona"), method: :get, remote: true, class: "dropdown-item border-bottom" do %>
                <span><%=t 'personas.create_persona'%></span>
            <% end %>    
            <%= link_to choose_template_groups_path(group_id: "", type: "survey"), method: :get, remote: true, class: "dropdown-item border-bottom " do %>
                <span><%=t 'surveys.create_survey'%></span>
            <% end %>
            <%= link_to new_group_path, method: :get, remote: true, class: "dropdown-item border-bottom " do %>
              <span><%=t 'groups.create_group_dropdown'%></span>
            <% end %>
            <%= link_to new_list_path, method: :get, remote: true, class: "dropdown-item" do %>
                      <span><%=t 'lists.create_list_dropdown'%></span>
                  <% end %>      
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if @groups.present? %>

  <div class="content">
    <div class="content-width">
      <div class="section">
        <div class="tool-bar-nav">
          <ul class="tool-bar">
            <li class="tool-bar__item tool-bar__item--active"><a href="#" class="tool-bar__link"><i class="fa fa-bars" aria-hidden="true"></i></a></li>
            <!--            <li class="tool-bar__item"><a href="#" class="tool-bar__link"><i class="fa fa-th-large" aria-hidden="true"></i></a></li>-->
          </ul>
          <div class="filteration-sorting">
            <ul class="filteration">
            </ul>
            <div class="sorting">
              <div class="dropdown">
                <a href="#" class="sorting-dropdown" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span><%= t 'dashboard.sort_by'%>:</span> <%= t 'dashboard.name'%> <i class="fa fa-angle-down" aria-hidden="true"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="#"><%= t 'dashboard.email'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.name'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.date'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.user'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.active'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.draft'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.finished'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.results'%></a>
                  <a class="dropdown-item" href="#"><%= t 'dashboard.customized'%></a>
                </div>
              </div>
            </div>

          </div>
        </div>


        <% @groups.each do |group| %>

          <div class="list-items list-items--company mt-10">
            <div class="list-items__info-wrapper">
              <%= link_to all_report_surveys_path(group) do %>
                <div class="list-items__photo list-items__photo--user border-gray">

                  <% if group.image.attached? %>
                    <%= image_tag group.image %>
                  <% else %>
                    <%= image_tag 'no-img-reports.png' %>
                  <% end %>

                </div>
              <% end %>

              <%= link_to all_report_surveys_path(group) do %>
                <div class="list-items__heading">
                  <h1 class="title-h1"><%= group.title %></h1>
                  <div class="list-items__export">
                    <h3 class="title-h3"><%= t 'surveys.group'%></h3>
                  </div>
                </div>
              <% end %>
            </div>

            <div class="list-items__body">

              <div class="list-items_statistic text-left list-items_statistic_align_170">
                <div class="list-items__item" style="margin:unset">
                  <div class="create-by"><%= t 'groups.created_by'%></div>
                  <span><%= creator_name(group.created_by_id) %></span>
                  <span><%= group.created_at.strftime("%b %d, %Y") %></span>
                </div>
              </div>

              <div class="list-items_statistic">
                <div class="list-items__item">
                  <span><%= group.custom_personas.count %></span>
                  <span><%= t 'reports.customized_personas'%></span>
                </div>

                <div class="list-items__item">
                  <span><%= group.surveys.undeleted_survey.where.not(survey_state: Survey.survey_states.key(0)).count %></span>
                  <span><%= t 'reports.results'%></span>
                </div>
              </div>

              <div class="list-items__buttons">
                <div class="list-items__view list-items__view--company list-add-icon">

                  <%= link_to all_report_surveys_path(group) do %>
                    <%= t 'reports.view_results'%><i class="fa fa-arrow-right ml-2" aria-hidden="true"></i>
                  <% end %>
                  

                </div>
              </div>

            </div>
          </div>
        <% end %>
        <div class="digg_pagination">
          <form action="<%= reports_path %>" class="r_drop_down">
            <%= t 'will_paginate.rows_per_page'%>:
             <%= select_tag('per_page', options_for_select([["1", 1], ["5", 5], ["10", 10], ["25", 25], ["50", 50]], params[:per_page].blank? ? 10 : params[:per_page] ), onchange: "this.form.submit();")%>
          </form>
          <div class="page_info">
            <%= page_entries_info @groups, :entry_name => 'lists' %>
          </div>
          <%= will_paginate @groups, :container => false , previous_label: "<i class='fa fa-angle-left' aria-hidden='true'></i>".html_safe, next_label: "<i class='fa fa-angle-right' aria-hidden='true'></i>".html_safe, page_links: false%>
        </div>

      </div>
    </div>
  </div>

<% else %>
  <div class="no-result-box-content">
    <div class="no-result-box text-center">
      <%= image_tag 'no-img-reports2.png', class: "mb-10"  %>
      <h2 class="no-result-text-theme mb-30"><%=t 'reports.dont_have_reports'%></h2>
      <% if policy($community_account).can_add_edit_delete_global? %>
        <p class="no-result-text-muted"><%= t 'reports.create_your_first_survey'%></p>
        <%= link_to "#{t 'reports.create_new_survey'}", 'javascript:;', class: "new-survey" %>
      <% end %>
    </div>
  </div>
<% end %>



<% if policy($community_account).can_add_edit_delete_global? %>
  <script type="text/javascript" charset="utf-8">
      $('.new-survey').click(function (event) {
          $.ajax({
              url: "<%= choose_template_groups_url %>",
              type: "get",
              dataType: 'script',
              data: {
                  group_id: $(this).data('id')
              },
              success: function (data) {
              }
          });
      });
  </script>
<% end %>

app/views/reports/show.html.erb
<%- tab_active = params[:tab].present? ? params[:tab] : '' %>
<%= render partial: 'chart_types/shared/chart_libraries' %>

<div class="container-fluid breads px-2 px-md-0 pt-3">

  <div class="d-inline-block action-bar__heading action-bar__heading--v2"><%= @group.title %>
    <span class="mx-5 mb-4 brand-sep">|</span>
  </div>
  <div class="d-inline-block brand-loyal">

                <span><p class="m-0 big"><%= @survey.title %></p>
                <p class="m-0 small"><%=t 'reports.sent'%> <%= @survey.updated_at.strftime("%b %d, %Y") %> <%=t 'reports.by'%> <%= @survey.creator.your_name %></p></span>
  </div>
  <ul class="nav nav-tabs mx-auto theme-nav-tabs" id="myTab" role="tablist">
    <li class="nav-item mr-md-4 mr-2">
      <a class="nav-link active show" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><%=t 'reports.results'%></a>
    </li>

      <li class="nav-item mx-md-4 mx-2">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#summary" role="tab" aria-controls="summary" aria-selected="false"><%=t 'reports.persona_summary'%></a>
      </li>

      <li class="nav-item mx-md-4 mx-2">
        <a class="nav-link" id="customized-persona-tab" data-toggle="tab" href="#customized" role="tab" aria-controls="customized" aria-selected="false"><%=t 'reports.customized_personas'%></a>
      </li>
  </ul>

</div>

<div class="container-fluid px-0">

  <div class="tab-content" id="myTabContent">

    <%= render partial: 'survey_results/results_tab' %>

      <%= render partial: 'survey_results/persona_summary_tab' %>

      <%= render partial: 'survey_results/persona_customized_tab' %>

  </div>

</div>
<script type="text/javascript">
    if ('<%=tab_active%>'.length > 0) {
        if ('<%=tab_active%>' == 'respondents'){
            $('[href="#tab-content-respondents"]').tab('show');
            $('[href="#summary"]').tab('show');
        }
        else if ('<%=tab_active%>' == 'custom') {
            $('[href="#customized"]').tab('show');
        }
        else{
            $('[href="#home"]').tab('show');
        }
    }
    else{
        $('[href="#home"]').tab('show');
    }
</script>